### PR TITLE
Cocoapods support

### PR DESCRIPTION
**Pull request by fassko**
#1 Cocoapods support

### CODE REVIEW

**Comment by Zaccc123** [comment]
Hey, @mattt any chance to merge this? I would love to use this great library with CocoaPods if is possible.

**Comment by mattt** [comment]
Unfortunately, CocoaPods already has a package called Money (https://cocoapods.org/pods/Money). If I choose a unique name for the podspec (e.g. "Money-FlightSchool"), I worry about some users assuming the incorrect pod name and getting confused. If I decide _not_ to publish to trunk, I'm concerned that the extra step for pointing to the repository would also cause confusion.

From [the CocoaPods docs](https://guides.cocoapods.org/using/the-podfile.html):

> The podspec file is expected to be in the root of the repo, if this library does not have a podspec file in its repo yet, you will have to use one of the approaches outlined in the sections below.

However, in the context of the page, I can't tell what is meant by "the sections below" is supposed to mean. I couldn't find the information they're referring to in the documentation.

I'm going to ask around to see what folks advise for this kind of situation.

**Comment by Zaccc123** [comment]
Oh, I think a unique name will be fine as long as `readme` is updated and perhaps also highlight it. I certainly also agree that naming it according to the repo name `Money` would be better. 

I did a quick check and find out that the current Pods `Money` [repo](https://github.com/danthorpe/Money) is actually archived. Maybe can speak with the owner and work something out too. Let me know if I can help, cheers.

**Comment by mattt** [comment]
@fassko One quick note for future reference — in Ruby, `#{...}` substitutions only work for strings delimited by double quotation marks (`"`), so [this line in your PR](https://github.com/Flight-School/Money/pull/5/commits/bbb1b6494c9f8ff1b61bbbe503ae756c0ef3a4ce#diff-f02ba06633a12f5ad6dda05141588fd7R24) wouldn't work as expected.

**Comment by fassko** [comment]
Thanks @mattt ! Fixed it.

**Comment by mattt** [comment]
Following the conventions from @flight-school/AnyCodable to work around namespacing issues, I just released this to CocoaPods under the name [Money-FlightSchool](https://cocoapods.org/pods/Money-FlightSchool).

**Pull request closed without merging**
